name: 1 - Teste e Validacao CI

on:
  push:
    branches: [ "main" ]

jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar codigo
        uses: actions/checkout@v4

      - name: Construir e testar container localmente
        run: |
          docker build -t app-teste .
          docker run -d --name app-teste -p 8080:80 app-teste
          sleep 2
          docker exec app-teste nginx -t
          curl -f http://127.0.0.1:8080 || exit 1
          docker stop app-teste