name: 2 - Build GHCR e Deploy VPS

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build_e_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar codigo
        uses: actions/checkout@v4

      - name: Login no GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Construir e Publicar Imagem no GHCR
        run: |
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/$REPO_LOWER:latest .
          docker push ghcr.io/$REPO_LOWER:latest
      - name: Testar conexao SSH
        run: |
          echo "Testando porta 22..."
          nc -vz -w 10 ${{ secrets.SSH_HOST }} 22

      - name: Deploy na VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

            cd ~/apps/Projeto_Integrador_Cloud_DevOps

            git pull origin main
            docker compose pull
            docker compose up -d --remove-orphans