name: 3 - Deploy na VPS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy_vps:
    runs-on: ubuntu-latest

    steps:
      - name: Executar comandos de Deploy na VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Conectado à VPS com sucesso!"
            
            # Se a pasta do projeto não existir na VPS, faz o clone
            if [ ! -d "projeto" ]; then
              git clone https://github.com/GuilhermeXisto/Projeto_Integrador_Cloud_DevOps.git projeto
            fi
            
            # Entra na pasta e atualiza o código
            cd projeto
            git pull origin main
            
            # Reinicia os containers com a versão nova
            docker compose down
            docker compose up -d --build
            echo "Deploy concluído e aplicação atualizada!"